port 6378
bind 0.0.0.0
daemonize yes
dir .
dbfilename dump.rdb
save 60 1
save 300 10
save 900 1
appendonly yes
appendfilename "appendonly.aof"
pidfile /tmp/classroom_redis.pid
logfile /tmp/classroom_redis.log
